################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from setuptools import setup

setup(
    name = "zyre_cffi",
    version = "2.0.1",
    license = "mpl-2.0",
    description = """Python cffi bindings of: an open-source framework for proximity-based p2p apps""",
    packages = ["zyre_cffi", ],
    setup_requires=["cffi"],
    cffi_modules=[
           "zyre_cffi/build.py:ffibuilder",
           "zyre_cffi/build.py:ffidestructorbuilder"
    ],
    install_requires=["cffi"],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
