#!/usr/bin/env python
# -*- coding: utf-8 -*-
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

from setuptools import setup

setup(
    name='zyre',
    description="""an open-source framework for proximity-based P2P apps""",
    version='2.0.1',
    url='http://github.com/zeromq/zyre',
    author_email='zeromq-dev@lists.zeromq.org',
    packages=['zyre'],
    package_dir={'zyre': 'zyre'},
    classifiers=[
        "Development Status :: 2.0.1",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: Implementation :: PyPy",
        "License :: OSI Approved :: Mozilla Public License 2.0",
    ],
    install_requires=["cffi>=1.0.0"],
    setup_requires=["cffi>=1.0.0"],
    cffi_modules=[
        "zyre/build_zyre_cffi.py:ffi",
        "zyre/build_zyre_cffi.py:ffiwrapper",
    ],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
