/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

#ifndef QML_ZYRE_PLUGIN_H
#define QML_ZYRE_PLUGIN_H

#include <QQmlExtensionPlugin>
#include <qqml.h>

class QmlZyre;
class QmlZyreAttached;
class QmlZyreEvent;
class QmlZyreEventAttached;

#include "QmlZyre.h"
#include "QmlZyreEvent.h"

class QmlZyrePlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA (IID "org.qt-project.Qt.QQmlExtensionInterface")
    
public:
    void registerTypes (const char *uri)
    {
        qmlRegisterType<QmlZyre> (uri, 1, 0, "QmlZyre");
        qmlRegisterType<QmlZyreAttached>();
        qmlRegisterType<QmlZyreEvent> (uri, 1, 0, "QmlZyreEvent");
        qmlRegisterType<QmlZyreEventAttached>();
    };
};

#endif

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
