# -*- coding: utf-8 -*-
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

__email__ = 'zeromq-dev@lists.zeromq.org'
__version__ = '2.0.1'

from zyre.Zyre import Zyre
from zyre.ZyreEvent import ZyreEvent

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
