/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
package org.zeromq.zyre;

import org.junit.Assert;
import org.junit.Test;

public class ZyreTest {
    @Test
    public void test () {
        Zyre zyre = new Zyre ();
        zyre.test (false);
    }
}
