################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from setuptools import setup

setup(
    name = "zyre",
    version = "2.0.1",
    license = "mplv2",
    description = """Python bindings of: an open-source framework for proximity-based p2p apps""",
    url = "https://github.com/zeromq/zyre",
    packages = ["zyre"],
    install_requires = [
        "czmq",
    ],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
