/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
#ifndef Q_QTZYRE_H
#define Q_QTZYRE_H

#include <QObject>
#include <QString>
#include <zyre.h>

#if defined(Q_OS_WIN)
#  if !defined(QT_ZYRE_EXPORT) && !defined(QT_ZYRE_IMPORT)
#    define QT_ZYRE_EXPORT
#  elif defined(QT_ZYRE_IMPORT)
#    if defined(QT_ZYRE_EXPORT)
#      undef QT_ZYRE_EXPORT
#    endif
#    define QT_ZYRE_EXPORT __declspec(dllimport)
#  elif defined(QT_ZYRE_EXPORT)
#    undef QT_ZYRE_EXPORT
#    define QT_ZYRE_EXPORT __declspec(dllexport)
#  endif
#else
#  define QT_ZYRE_EXPORT
#endif

//  Opaque class structures to allow forward references
class QZyre;
class QZyreEvent;
class QZcert;
class QZmsg;
class QZlist;
class QZsock;
class QZhash;
class QZframe;

//  Public API classes
#include "qzyre.h"
#include "qzyreevent.h"
#include "qzcert.h"
#include "qzmsg.h"
#include "qzlist.h"
#include "qzsock.h"
#include "qzhash.h"
#include "qzframe.h"

#endif //  Q_ZYRE_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
