/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "zyre.h"
#include "../../native/include/org_zeromq_zyre_ZyreEvent.h"

JNIEXPORT jlong JNICALL
Java_zyre_event__1_1new (JNIEnv *env, jclass c, jlong self)
{
    jlong new_ = (jlong) zyre_event_new ((zyre_t *) self);
    return new_;
}

JNIEXPORT void JNICALL
Java_zyre_event__1_1destroy (JNIEnv *env, jclass c, jlong self_p)
{
    zyre_event_destroy ((zyre_event_t **) &self_p);
}

JNIEXPORT jint JNICALL
Java_zyre_event__1_1type (JNIEnv *env, jclass c, jlong self)
{
    jint type_ = (jint) zyre_event_type ((zyre_event_t *) self);
    return type_;
}

JNIEXPORT jstring JNICALL
Java_zyre_event__1_1sender (JNIEnv *env, jclass c, jlong self)
{
    char *sender_ = (char *) zyre_event_sender ((zyre_event_t *) self);
    jstring string = (*env)->NewStringUTF (env, sender_);
    return string;
}

JNIEXPORT jstring JNICALL
Java_zyre_event__1_1name (JNIEnv *env, jclass c, jlong self)
{
    char *name_ = (char *) zyre_event_name ((zyre_event_t *) self);
    jstring string = (*env)->NewStringUTF (env, name_);
    return string;
}

JNIEXPORT jstring JNICALL
Java_zyre_event__1_1address (JNIEnv *env, jclass c, jlong self)
{
    char *address_ = (char *) zyre_event_address ((zyre_event_t *) self);
    jstring string = (*env)->NewStringUTF (env, address_);
    return string;
}

JNIEXPORT jlong JNICALL
Java_zyre_event__1_1headers (JNIEnv *env, jclass c, jlong self)
{
    jlong headers_ = (jlong) zyre_event_headers ((zyre_event_t *) self);
    return headers_;
}

JNIEXPORT jstring JNICALL
Java_zyre_event__1_1header (JNIEnv *env, jclass c, jlong self, jstring name)
{
    char *name_ = (char *) (*env)->GetStringUTFChars (env, name, NULL);
    char *header_ = (char *) zyre_event_header ((zyre_event_t *) self, name_);
    jstring string = (*env)->NewStringUTF (env, header_);
    (*env)->ReleaseStringUTFChars (env, name, name_);
    return string;
}

JNIEXPORT jstring JNICALL
Java_zyre_event__1_1group (JNIEnv *env, jclass c, jlong self)
{
    char *group_ = (char *) zyre_event_group ((zyre_event_t *) self);
    jstring string = (*env)->NewStringUTF (env, group_);
    return string;
}

JNIEXPORT jlong JNICALL
Java_zyre_event__1_1msg (JNIEnv *env, jclass c, jlong self)
{
    jlong msg_ = (jlong) zyre_event_msg ((zyre_event_t *) self);
    return msg_;
}

JNIEXPORT void JNICALL
Java_zyre_event__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zyre_event_test ((bool) verbose);
}

