/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "zyre.h"
#include "../../native/include/org_zeromq_zyre_Zyre.h"

JNIEXPORT jlong JNICALL
Java_zyre__1_1new (JNIEnv *env, jclass c, jstring name)
{
    char *name_ = (char *) (*env)->GetStringUTFChars (env, name, NULL);
    jlong new_ = (jlong) zyre_new (name_);
    (*env)->ReleaseStringUTFChars (env, name, name_);
    return new_;
}

JNIEXPORT void JNICALL
Java_zyre__1_1destroy (JNIEnv *env, jclass c, jlong self_p)
{
    zyre_destroy ((zyre_t **) &self_p);
}

JNIEXPORT jstring JNICALL
Java_zyre__1_1uuid (JNIEnv *env, jclass c, jlong self)
{
    char *uuid_ = (char *) zyre_uuid ((zyre_t *) self);
    jstring string = (*env)->NewStringUTF (env, uuid_);
    return string;
}

JNIEXPORT jstring JNICALL
Java_zyre__1_1name (JNIEnv *env, jclass c, jlong self)
{
    char *name_ = (char *) zyre_name ((zyre_t *) self);
    jstring string = (*env)->NewStringUTF (env, name_);
    return string;
}

JNIEXPORT void JNICALL
Java_zyre__1_1set_header (JNIEnv *env, jclass c, jlong self, jstring name, jstring format)
{
    char *name_ = (char *) (*env)->GetStringUTFChars (env, name, NULL);
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    zyre_set_header ((zyre_t *) self, name_, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, name, name_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
}

JNIEXPORT void JNICALL
Java_zyre__1_1set_verbose (JNIEnv *env, jclass c, jlong self)
{
    zyre_set_verbose ((zyre_t *) self);
}

JNIEXPORT void JNICALL
Java_zyre__1_1set_port (JNIEnv *env, jclass c, jlong self, jint port_nbr)
{
    zyre_set_port ((zyre_t *) self, (int) port_nbr);
}

JNIEXPORT void JNICALL
Java_zyre__1_1set_interval (JNIEnv *env, jclass c, jlong self, jlong interval)
{
    zyre_set_interval ((zyre_t *) self, (size_t) interval);
}

JNIEXPORT void JNICALL
Java_zyre__1_1set_interface (JNIEnv *env, jclass c, jlong self, jstring value)
{
    char *value_ = (char *) (*env)->GetStringUTFChars (env, value, NULL);
    zyre_set_interface ((zyre_t *) self, value_);
    (*env)->ReleaseStringUTFChars (env, value, value_);
}

JNIEXPORT jint JNICALL
Java_zyre__1_1set_endpoint (JNIEnv *env, jclass c, jlong self, jstring format)
{
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    jint set_endpoint_ = (jint) zyre_set_endpoint ((zyre_t *) self, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
    return set_endpoint_;
}

JNIEXPORT void JNICALL
Java_zyre__1_1gossip_bind (JNIEnv *env, jclass c, jlong self, jstring format)
{
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    zyre_gossip_bind ((zyre_t *) self, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
}

JNIEXPORT void JNICALL
Java_zyre__1_1gossip_connect (JNIEnv *env, jclass c, jlong self, jstring format)
{
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    zyre_gossip_connect ((zyre_t *) self, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
}

JNIEXPORT jint JNICALL
Java_zyre__1_1start (JNIEnv *env, jclass c, jlong self)
{
    jint start_ = (jint) zyre_start ((zyre_t *) self);
    return start_;
}

JNIEXPORT void JNICALL
Java_zyre__1_1stop (JNIEnv *env, jclass c, jlong self)
{
    zyre_stop ((zyre_t *) self);
}

JNIEXPORT jint JNICALL
Java_zyre__1_1join (JNIEnv *env, jclass c, jlong self, jstring group)
{
    char *group_ = (char *) (*env)->GetStringUTFChars (env, group, NULL);
    jint join_ = (jint) zyre_join ((zyre_t *) self, group_);
    (*env)->ReleaseStringUTFChars (env, group, group_);
    return join_;
}

JNIEXPORT jint JNICALL
Java_zyre__1_1leave (JNIEnv *env, jclass c, jlong self, jstring group)
{
    char *group_ = (char *) (*env)->GetStringUTFChars (env, group, NULL);
    jint leave_ = (jint) zyre_leave ((zyre_t *) self, group_);
    (*env)->ReleaseStringUTFChars (env, group, group_);
    return leave_;
}

JNIEXPORT jlong JNICALL
Java_zyre__1_1recv (JNIEnv *env, jclass c, jlong self)
{
    jlong recv_ = (jlong) zyre_recv ((zyre_t *) self);
    return recv_;
}

JNIEXPORT jint JNICALL
Java_zyre__1_1whisper (JNIEnv *env, jclass c, jlong self, jstring peer, jlong msg_p)
{
    char *peer_ = (char *) (*env)->GetStringUTFChars (env, peer, NULL);
    jint whisper_ = (jint) zyre_whisper ((zyre_t *) self, peer_, (zmsg_t **) &msg_p);
    (*env)->ReleaseStringUTFChars (env, peer, peer_);
    return whisper_;
}

JNIEXPORT jint JNICALL
Java_zyre__1_1shout (JNIEnv *env, jclass c, jlong self, jstring group, jlong msg_p)
{
    char *group_ = (char *) (*env)->GetStringUTFChars (env, group, NULL);
    jint shout_ = (jint) zyre_shout ((zyre_t *) self, group_, (zmsg_t **) &msg_p);
    (*env)->ReleaseStringUTFChars (env, group, group_);
    return shout_;
}

JNIEXPORT jint JNICALL
Java_zyre__1_1whispers (JNIEnv *env, jclass c, jlong self, jstring peer, jstring format)
{
    char *peer_ = (char *) (*env)->GetStringUTFChars (env, peer, NULL);
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    jint whispers_ = (jint) zyre_whispers ((zyre_t *) self, peer_, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, peer, peer_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
    return whispers_;
}

JNIEXPORT jint JNICALL
Java_zyre__1_1shouts (JNIEnv *env, jclass c, jlong self, jstring group, jstring format)
{
    char *group_ = (char *) (*env)->GetStringUTFChars (env, group, NULL);
    char *format_ = (char *) (*env)->GetStringUTFChars (env, format, NULL);
    jint shouts_ = (jint) zyre_shouts ((zyre_t *) self, group_, "%s", format_);
    (*env)->ReleaseStringUTFChars (env, group, group_);
    (*env)->ReleaseStringUTFChars (env, format, format_);
    return shouts_;
}

JNIEXPORT jlong JNICALL
Java_zyre__1_1peers (JNIEnv *env, jclass c, jlong self)
{
    jlong peers_ = (jlong) zyre_peers ((zyre_t *) self);
    return peers_;
}

JNIEXPORT jlong JNICALL
Java_zyre__1_1own_groups (JNIEnv *env, jclass c, jlong self)
{
    jlong own_groups_ = (jlong) zyre_own_groups ((zyre_t *) self);
    return own_groups_;
}

JNIEXPORT jlong JNICALL
Java_zyre__1_1peer_groups (JNIEnv *env, jclass c, jlong self)
{
    jlong peer_groups_ = (jlong) zyre_peer_groups ((zyre_t *) self);
    return peer_groups_;
}

JNIEXPORT jstring JNICALL
Java_zyre__1_1peer_address (JNIEnv *env, jclass c, jlong self, jstring peer)
{
    char *peer_ = (char *) (*env)->GetStringUTFChars (env, peer, NULL);
    char *peer_address_ = (char *) zyre_peer_address ((zyre_t *) self, peer_);
    jstring string = (*env)->NewStringUTF (env, peer_address_);
    zstr_free (&peer_address_);
    (*env)->ReleaseStringUTFChars (env, peer, peer_);
    return string;
}

JNIEXPORT jstring JNICALL
Java_zyre__1_1peer_header_value (JNIEnv *env, jclass c, jlong self, jstring peer, jstring name)
{
    char *peer_ = (char *) (*env)->GetStringUTFChars (env, peer, NULL);
    char *name_ = (char *) (*env)->GetStringUTFChars (env, name, NULL);
    char *peer_header_value_ = (char *) zyre_peer_header_value ((zyre_t *) self, peer_, name_);
    jstring string = (*env)->NewStringUTF (env, peer_header_value_);
    zstr_free (&peer_header_value_);
    (*env)->ReleaseStringUTFChars (env, peer, peer_);
    (*env)->ReleaseStringUTFChars (env, name, name_);
    return string;
}

JNIEXPORT jlong JNICALL
Java_zyre__1_1socket (JNIEnv *env, jclass c, jlong self)
{
    jlong socket_ = (jlong) zyre_socket ((zyre_t *) self);
    return socket_;
}

JNIEXPORT void JNICALL
Java_zyre__1_1version (JNIEnv *env, jclass c, jint major, jint minor, jint patch)
{
    zyre_version ((int *) &major, (int *) &minor, (int *) &patch);
}

JNIEXPORT void JNICALL
Java_zyre__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zyre_test ((bool) verbose);
}

