/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_zyre_ZyreEvent */

#ifndef _Included_org_zeromq_zyre_ZyreEvent
#define _Included_org_zeromq_zyre_ZyreEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1new
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __type
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __peerUuid
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1peerUuid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __peerName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1peerName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __peerAddr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1peerAddr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __headers
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1headers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __header
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1header
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __group
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __msg
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1msg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __getMsg
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1getMsg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
