/*  =========================================================================
    zyre_classes - private header file

    Copyright (c) 1991-2012 iMatix Corporation -- http://www.imatix.com     
    Copyright other contributors as noted in the AUTHORS file.              
                                                                            
    This file is part of Zyre, an open-source framework for proximity-based 
    peer-to-peer applications -- See http://zyre.org.                       
                                                                            
    This is free software; you can redistribute it and/or modify it under   
    the terms of the GNU Lesser General Public License as published by the  
    Free Software Foundation; either version 3 of the License, or (at your  
    option) any later version.                                              
                                                                            
    This software is distributed in the hope that it will be useful, but    
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTA-   
    BILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General  
    Public License for more details.                                        
                                                                            
    You should have received a copy of the GNU Lesser General Public License
    along with this program. If not, see http://www.gnu.org/licenses/.      
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __ZYRE_CLASSES_H_INCLUDED__
#define __ZYRE_CLASSES_H_INCLUDED__

//  External API
#include "../include/zyre.h"

//  Internal API
#include "zyre_peer.h"
#include "zyre_group.h"
#include "zyre_node.h"

//  Private constants    
#define PEER_EVASIVE	3000 //                    3 seconds' silence is evasive
#define PEER_EXPIRED	5000 //                    5 seconds' silence is expired
#define REAP_INTERVAL	1000 //                   Once per second
#endif
